identifier:
  image: semtech/mu-identifier
  links:
    - dispatcher:dispatcher
  ports:
    - "80:80"
dispatcher:
  image: semtech/mu-dispatcher
  links:
    - login:login
    - comments:comments
    - fileManager:file-manager
  volumes:
    - config:/config
db:
  image: tenforce/virtuoso:virtuoso-v7.2.0-latest
  environment:
    SPARQL_UPDATE: "true"
  ports:
    - "8890:8890"
login:
  image: semtech/mu-login-service
  links:
    - db:database
comments:
  image: semtech/mu-page-comments-service
  links:
    - db:database
fileManager:
  image: semtech/mu-file-manager
  links: 
    - db:database
  volumes:
    - /tmp/storage:/home/app/storage
  environment:
    MU_APPLICATION_GRAPH: http://mu.semte.ch/app
    SECRET_KEY_BASE: my-secret-production-key-for-rails